/**:
  ros__parameters:
    camera_info_url: package://hnurm_bringup/config/camera_info.yaml
    path: "/home/lh/test_data/video/1.avi"
    frame_rate: 10
    start_frame: 0
    frame_id: "camera_optical_frame"
    keep_looping: true              #是否循环播放
